create table t_movie
(
    movie_id    int(4) unsigned auto_increment comment '电影id'
        primary key,
    name        varchar(50)               null comment '电影名称',
    poster      varchar(100)              null comment '电影海报',
    director    varchar(20)               null comment '导演',
    actor       varchar(100)              null comment '主演',
    movie_long  varchar(20)               null comment '电影片长',
    language    varchar(50)               null comment '电影语言版本',
    intro       text                      null comment '电影简介',
    type        varchar(50)               null comment '电影类型',
    public_date varchar(20)               null comment '电影上映时间',
    wish_num    int(4) unsigned default 0 null comment '想看人数',
    score       decimal(4, 1)             null comment '电影综合评分'
)
    collate = utf8_unicode_ci;

INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (1, '驯龙高手3', '/images/movie/hot1.jpg', '迪恩·德布洛斯', '刘昊然', '130分钟', '英语', '统领伯克岛的酋长嗝嗝（刘昊然 配音），与阿丝翠德（亚美莉卡·费雷拉 配音）共同打造了一个奇妙而热闹的飞龙乌托邦。一只雌性光煞飞龙的意外出现，加上一个前所未有的威胁的到来，令嗝嗝和没牙仔不得不离开自己唯一的家园，前往他们本以为只存在于神话之中的隐秘之境。在发现自己真正的命运之后，飞龙与骑士将携手殊死奋战，保护他们所珍爱的一切。', '动漫', '2021-4-30', 0, 0.0);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (3, '夏目友人帐', '/images/movie/hot3.jpg', '大森贵弘', '村濑步', '105分钟', '日语', '夏目（神谷浩史 配音）在一次归还妖怪名字的过程中，结识了外祖母玲子（小林沙苗 配音）的旧识津村容莉枝岛本须美 配音）和她的儿子椋雄（高良健吾 配音）。在与其接触后，夏目的“保镖”猫咪老师（井上和彦 配音）竟第一次意外分裂成了三只！夏目能否解决危机？这对母子又与妖怪有何关系？', '言情', '2018-11-13', 1, null);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (4, '比悲伤更悲伤的故事', '/images/movie/hot4.jpg', '林孝谦', '陈庭妮', '105分钟', '国语', '唱片制作人张哲凯（刘以豪 饰）和王牌作词人宋媛媛（陈意涵 饰）相依为命，两人自幼身世坎坷只有彼此为伴，他们是亲人、是朋友，也彷佛是命中注定的另一半。父亲罹患遗传重症而被母亲抛弃的哲凯，深怕自己随时会发病不久人世，始终没有跨出友谊的界线对媛媛展露爱意。眼见哲凯的病情加重，他暗自决定用剩余的生命完成他们之间的终曲，再为媛媛找个可以托付一生的好男人。这时，事业有成温柔体贴的医生（张书豪 饰）适时的出现让他成为照顾媛媛的最佳人选，二人按部就班发展着关系。一切看似都在哲凯的计划下进行。然而，故事远比这里所写更要悲伤', '言情', '2018-9-1', 0, 0.0);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (5, '惊奇队长', '/images/movie/hot5.jpg', '瑞安·弗雷克', '本·门德尔森', '108分钟', '英语', '卡罗尔·丹弗斯（布丽·拉尔森 饰）是克里人的精英部队一员，但她挣扎着回忆过去，对于怎么获得超能力、以及之前的人生等超能力之前的人生，她只在梦中有片段不成章的记忆，这层困扰引起的情绪波动也进而影响她对超能力的掌控。所幸，在星际战队指挥官（裘德·洛 饰）的调教之下，卡罗尔·丹弗斯学会如何控制自己的超能力。一次外星任务中，卡罗尔·丹弗斯因故来到了地球，并遇到还是低阶探员的尼克·弗瑞（塞缪尔·杰克逊 饰），卡罗尔·丹弗斯与尼克·弗瑞一起追捕在地球惹事的变形人塔罗斯（本·门德尔森 饰），同时，也发现自己如何获得超能力。', '爱情', '2021-6-11', 4, 8.5);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (6, '我的英雄学院', '/images/movie/hot6.jpg', '长崎健司', '生濑胜久', '96分钟', '日语', '讲述在绝大多数人都有超能力的未来时代，没有天赋的异能少年，如何凭努力与坚持打破绝境，成长为最强英雄，守卫世界和平的故事。 剧场版以移动科研都市“我之岛”为舞台，描绘正反两派的殊死激战。在第一英雄被困之际，少年与英雄科同学拼死克敌，却在无意中探得隐秘真相，剧情随之反转', '科幻', '2018-8-13', 2, null);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (7, '我叫为何', '/images/movie/1.jpg', '李小军', '乔新峰', '86分钟', '国语', '讲述了两个技术宅男为何和吕相立志设计一款以圣朝名将无束为主角的火爆游戏。作为战神无束的死忠粉丝，为何在设计游戏的过程中，意外穿越到了圣朝，有机会亲眼目睹无束驱除西土的宏大场面。', '喜剧', '2019-8-20', 4, 9.0);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (8, '如影随心', '/images/movie/2.jpg', '霍建起', '马苏', '96分钟', '国语', '小提琴家陆松（陈晓 饰）与室内设计师文罂（杜鹃 饰）巴黎邂逅，不打不相识，彼此迷恋越陷越深。爱情之名怂恿着他们为爱再大胆一次，走出各自问题满满的情感关系。仿佛只要现任变前任，幸福就唾手可得。然而前任们也都是战士，文罂的前任郑可（华少 饰）是个理性至极的医生，陆松的前任刘娟（马苏 饰）则在情感社区开启了喋喋不休的骂战，是继续坚持对爱的信仰，还是选择放下与原谅重新开始？现代都市情感危机在北京与巴黎街头上演。越是深爱的，往往也正是痛苦的源头，爱情，像是影子，抓不住却也离不开，如影随心', '爱情', '2019-9-11', 2, null);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (9, '转型团伙', '/images/movie/3.jpg', '吴镇宇', '吴镇宇', '90分钟', '国语', '过气影帝宇哥（吴镇宇 饰）与当红童星费曼（费曼 饰）因一场拍摄意外而陷入黑帮纷争的故事。失忆的宇哥意外“入戏”，以为自己就是真正的社团大哥，为了赚钱照顾儿子决定重出江湖，殊不知时代已经改变，引发一连串令人啼笑皆非的乌龙事件，更上演了险象环生的黑帮纷争', '剧情', '2019-7-28', 2, null);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (10, '境界', '/images/movie/4.jpg', '佐藤信介', '真野惠里菜', '108分钟', '日语', '从小异于常人的黑崎一护（福士苍汰 饰），在一次机缘巧合下遭遇女死神“朽木露琪亚”（杉咲花 饰）。 露琪亚是将灵魂从现实世界引领到尸魂界的收魂者之一，他们为保护人类 不被“虚” 侵害，一直在与这些怪物战斗。在与一只异常强大的“虚” 战斗时，露琪亚身负重伤，无奈只能将死神 的力量暂时转给黑崎一护，让其代为战斗。两人经过一段时间的磨合后并肩战斗，终于战胜了当年害死一护母亲的“虚”，但在这期间，露琪亚的兄长朽木白哉（石原贵雅 饰）强迫她不顾黑崎一护的生命安危收回法力。露琪亚为保护一护，拖延到与“虚”的战斗结束，并清除了一护的记忆', '动作', '2019-11-12', 1, null);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (11, '神奇乐园历险记', '/images/movie/5.jpg', 'Dylan Brown', '基南·汤普森', '95分钟', '英语', '古灵精怪的十二岁女孩朱妮（Sofia Mali 配音），偶然间她发现了一座神奇的乐园。小朱妮在乐园里遇到了憨厚可掬的蓝熊布默（肯·哈德森·坎贝尔 配音），善良的疣猪格里塔（米拉·库尼斯 配音），贫嘴的豪猪史蒂夫（约翰·奥利弗 配音），滑稽搞笑的海狸兄弟库珀（郑肯 配音）和格斯（基南·汤普森 配音），充满奇幻想象力的首领和乐园里炙手可热的动物明星猴子花生，并很快和它们成为朋友。这座隐藏在森林中的神奇乐园不仅有着形形色色的动物，还有很多惊险刺激的游乐设施。但从动物朋友口中，小朱妮得知乐园已经衰败无法运营。很快，小朱妮就意识到这座神奇乐园和她之前想象中的乐园一模一样。只有她能拯救这座已经没落的乐园。于是，她和动物朋友们组成了一只小分队，希望帮助乐园重现昔日繁华。', '冒险', '2019-12-1', 0, null);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (12, '毕业旅行之逍遥骑士', '/images/movie/6.jpg', '郭奎永', '田雨', '90分钟', '国语', '高考落榜的文艺少年杨风（张朔祯 饰）梦想成为一个“嬉皮士”浪子，并誓要在毕业旅行中完成自己的浪子清单：打架、泡妞、吸烟喝酒、打坐冥想、和摇滚歌手交朋友……他在好友陈火（赵一凡 饰）的相助下伪装成“逍遥骑士”，想借助漂亮师姐思思（安紫依 饰）完成自己的“破处之旅”，却没想到思思也暗藏自己的“少女成人计划”，“逍遥路上”演绎啼笑皆非的动人故事。', '青春', '2019-11-11', 2, 0.0);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (13, '复仇者联盟4', '/images/movie/7.jpg', '乔·罗素', '小罗伯特·唐尼', '181分钟', '英语', '改编自漫威漫画，也是漫威电影宇宙第22部影片。复仇者联盟的一众超级英雄，必须抱着牺牲一切的信念，与史上最强大反派灭霸殊死一搏，阻止其摧毁宇宙的邪恶计划。', '动作', '2019-4-24', 3, 0.0);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (14, '撞死了一只羊', '/images/movie/8.jpg', '万玛才旦', '金巴', '87分钟', '国语', '司机金巴（金巴 饰）在路上撞死了一只羊，决意超度此羊；杀手金巴（更登彭措 饰）即将找到杀父仇人，准备报仇雪恨。阴差阳错，杀手金巴搭上了司机金巴的卡车。于是，两个叫金巴的男人的命运便神秘地联系在了一起，一段惊心动魄的旅程开始……', '剧情', '2019-8-12', 0, null);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (15, '云雾笼罩的山峰', '/images/movie/9.jpg', '左志国', '王海涛', '92分钟', '国语', '一位年轻的父亲为了筹钱医治自己病重的爱女，又要不到拖欠的赔款，被迫铤而走险绑架了老板的女儿。然而他不知道的是，在这座幽静的山里，还有其他人带着不同的目的和欲望参与了这件事情，一座山上、一日之内、六组人马，各自的贪念在错综复杂的因果之下，逐渐失控，转向不可预知的方向。罪恶之中，谁能逃脱命运的审判？', '悬疑', '2019-7-14', 1, null);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (16, '九克拉战栗', '/images/movie/10.jpg', '林峻兆', '付然', '86分钟', '国语', '珠宝店店员包小萱鬼迷心窍捡走车祸死者——女老板虞娜的钻戒，这是枚被恶魔诅咒的钻戒。 瞬间，包小萱被虞娜灵魂附身，同时，这场车祸似乎也从没发生过。随之各种恐怖事件纷纷降临在被虞娜灵魂附身的包小萱身上……', '恐怖', '2019-7-1', 0, null);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (17, '绿皮书', '/images/movie/hot7.jpg', '皮特·法雷里', '维果·莫腾森', '130分钟', '英语', '一名黑人钢琴家，为前往种族歧视严重的南方巡演，找了一个粗暴的白人混混做司机。在一路开车南下的过程里，截然不同的两人矛盾不断，引发了不少争吵和笑料。但又在彼此最需要的时候，一起共渡难关。行程临近结束，两人也慢慢放下了偏见...... 绿皮书，是一本专为黑人而设的旅行指南，标注了各城市中允许黑人进入的旅店、餐馆。电影由真实故事改编。', '剧情', '2019-3-1', 3, 6.0);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (18, '阿丽塔', '/images/movie/hot8.jpg', '罗伯特·罗德里', '罗莎·萨拉查', '123分钟', '英语', '未来26世纪，科技发展，人类与机械改造人共存，弱肉强食是钢铁城唯一的生存法则。依德（克里斯托夫·沃尔兹 饰）是钢铁城著名的改造人医生，他在垃圾场发现了一个半机械少女残躯，依德医生将其拯救后为她取名阿丽塔（罗莎·萨拉扎尔 饰）。阿丽塔虽然重获生命却失去了记忆，如一个新生儿一样对这个世界充满新鲜感。在依德医生与好友雨果（基恩·约翰逊 饰）的帮助下，她逐步适应着新生活和街头险恶。一次偶然的机会，阿丽塔发现自己竟有着惊人的战斗天赋。 一次次猎杀激发着她的觉醒，阿丽塔逐渐明白自己注定为战斗而生，为正义而战。一场揭开自己身世之谜，并打破宇宙旧秩序的史诗级冒险之旅就这样展开。', '动作', '2019-2-22', 0, null);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (19, '狗眼看人心', '/images/movie/hot9.jpg', '吴楠', '黄磊', '91分钟', '国语', '本片讲述了一桩因“狗咬狗”引发的连锁故事。余峰（黄磊 饰）、亮亮（闫妮 饰）、余一诺（安吉 饰）家的小狗妮蔻，为了救主人被隔壁藏獒咬成重伤，有权有势的藏獒主人却对余峰一家百般刁难。面对种种不公，余峰不再忍气吞声，发誓要为小狗讨回公道，但柴女士（汤唯 饰）等人的出现，却让矛盾进一步激化......狗生不易，小狗愿意用生命守护我们，我们又能为它做什么呢？', '剧情', '2019-4-20', 0, 0.0);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (20, '祈祷落幕时', '/images/movie/hot10.jpg', '福泽克雄', '阿部宽', '119分钟', '日语', '在东京都葛饰区小菅的某座公寓里，发现了一具被勒死的女性遗体。被害者是在清洁公司上班、住在滋贺县的押谷道子（中岛博子 饰）。而杀人现场的住户越川睦夫也下落不明。而以松宫（沟端淳平 饰）等警视厅搜查一科的刑警们查不出越川与押谷道子有何交集，案件调查陷入困境。尽管查明押谷道子是为了拜访她的同学，即导演浅居博美（松岛菜菜子 饰）才来东京的，但博美与越川之间也找不出什么交集。这时，案发地点附近发现了被烧死的尸体，松宫怀疑两者有关联。从遗物中，发现了写有日本桥周围12座桥名的文字。知道此事后加贺恭一郎（阿部宽 饰）非常激动，因为那东西与他的亡母大有关联。', '剧情', '2021-6-15', 2, 0.0);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (29, '大侦探皮卡丘', '/images/movie/1557131178228.jpg', '卡梅隆', '皮卡丘', '104分钟', '英语', '蒂姆·古德曼（贾斯提斯·史密斯 饰） 为寻找下落不明的父亲来到莱姆市，意外与父亲的前宝可梦搭档大侦探皮卡丘（瑞恩·雷诺兹 配音）相遇，并惊讶地发现自己是唯一能听懂皮卡丘说话的人类，他们决定组队踏上揭开真相的刺激冒险之路。探案过程中他们邂逅了各式各样的宝可梦，并意外发现了一个足以毁灭整个宝可梦宇宙的惊天阴谋。', '冒险', '2019-5-20', 3, 0.0);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (33, '罗马', '/images/movie/1557394982584.jpg', '张三', '李四', '1200分钟', '粤语', '嘻嘻嘻嘻嘻', '言情', '2019-5-23', 4, 7.0);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (34, '来电狂响', '/images/movie/1557457509601.jpg', '张三', '董大伟', '130分钟', '国语', '七个好友聚餐，有人提议大家玩一个将手机公开的游戏：与在场所有人分享当晚收到的每一条短信、每一个电话，每一个弹窗，由此掀开了一场轩然大波。 一条短信，拆散一对恩爱夫妻；一个电话，推翻多年发小感情……数字时代，小小手机藏了无数秘密，当手机变成锋利的利刃，当聚餐局变成“揭 秘局”，信任危机过后他们能否跨越信任危机，重新思考彼此之间的亲密关系………..', '悬疑', '2019-5-31', 2, 0.0);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (35, '雪暴', '/images/movie/1557555972902.jpg', '张三', '李四', '120分钟', '国语', '无', '喜剧', '2019-5-17', 1, 0.0);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (36, '一个母亲的复仇', '/images/movie/1563173524205.jpg', '王明', '张三', '118分钟', '国语', '一个母亲的复仇', '悬疑', '2019-11-14', 1, 0.0);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (37, '蜘蛛侠：英雄远征', '/images/movie/1563173216299.jpg', '大奔', '蜘蛛', '180分钟', '英语', '故事全面延续“复联4”，蜘蛛侠志承钢铁侠远征欧洲，独挑大梁对抗群敌！新角色“神秘客”穿越多元宇宙霸气登场！神盾局局长尼克·弗瑞回归领军！“漫威新铁三角”组合强势出击！全新蜘蛛战衣酷炫升级！史诗对决燃爆今夏突破想象极限！', '科幻', '2019-7-11', 0, null);
INSERT INTO db_film.t_movie (movie_id, name, poster, director, actor, movie_long, language, intro, type, public_date, wish_num, score) VALUES (38, '银河补习班', '/images/movie/1563180596034.jpg', '李四', '王五', '156分钟', '英语', '银河补习班', '喜剧', '2019-7-11', 0, null);